# Generated by Django 5.2.4 on 2025-07-23 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0002_alter_blog_author_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="author_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
